### ISSUE TITLE
如果去掉QQ登录应该改动哪些呢？

### ISSUE THREAD

**Issue by Eleven-is-cool** [373675032/moti-cloud#4]
QQ那个互联平台后面创建应用的认证要好久，还得等域名备案完成，请问一下如果不想用QQ登录应该改动哪些呢？

**Comment by waiting-windy** [comment]
你可以看源码，登录的controller，内置了一个调试用的借口"/admin""，别忘了在拦截器放开"/admin"接口

**Comment by Eleven-is-cool** [comment]
> 你可以看源码，登录的controller，内置了一个调试用的借口"/admin""，别忘了在拦截器放开"/admin"接口

好的，十分感谢！

**Comment by waiting-windy** [comment]
请问您使用该项目做些什么呢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Eleven-is-cool"<notifications@github.com&gt;; 
发送时间: 2020年4月20日(星期一) 晚上6:40
收件人: "373675032/moti-cloud"<moti-cloud@noreply.github.com&gt;; 
抄送: "小泽"<964879015@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [373675032/moti-cloud] 如果去掉QQ登录应该改动哪些呢？ (#4)





  
你可以看源码，登录的controller，内置了一个调试用的借口"/admin""，别忘了在拦截器放开"/admin"接口
  
好的，十分感谢！

**Comment by Eleven-is-cool** [comment]
噢噢，我只是单纯来学习springboot而已。没那个qq登录往下弄不了。

**Comment by Eleven-is-cool** [comment]
> 请问您使用该项目做些什么呢
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Eleven-is-cool"<notifications@github.com&gt;; 发送时间: 2020年4月20日(星期一) 晚上6:40 收件人: "373675032/moti-cloud"<moti-cloud@noreply.github.com&gt;; 抄送: "小泽"<964879015@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 主题: Re: [373675032/moti-cloud] 如果去掉QQ登录应该改动哪些呢？ (#4) 你可以看源码，登录的controller，内置了一个调试用的借口"/admin""，别忘了在拦截器放开"/admin"接口 好的，十分感谢！ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

你好，是访问```http://127.0.0.1:8080/moti-cloud/admin```吗？然后加入拦截器时，
```registry.addInterceptor(new LoginHandlerInterceptor()).addPathPatterns("/**").excludePathPatterns("/","/admin".....);```
这样吗？可是我仍会被重定向到登录页。

**Comment by waiting-windy** [comment]
你把moti啥的去掉啊，那东西哪来的？


 
---原始邮件---
发件人: "Eleven-is-cool"<notifications@github.com&gt;
发送时间: 2020年4月21日 22:21:53
收件人: "373675032/moti-cloud"<moti-cloud@noreply.github.com&gt;;
抄送: "nanfeng"<964879015@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [373675032/moti-cloud] 如果去掉QQ登录应该改动哪些呢？ (#4)




  
请问您使用该项目做些什么呢
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Eleven-is-cool"<notifications@github.com&gt;; 发送时间: 2020年4月20日(星期一) 晚上6:40 收件人: "373675032/moti-cloud"<moti-cloud@noreply.github.com&gt;; 抄送: "小泽"<964879015@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 主题: Re: [373675032/moti-cloud] 如果去掉QQ登录应该改动哪些呢？ (#4) 你可以看源码，登录的controller，内置了一个调试用的借口"/admin""，别忘了在拦截器放开"/admin"接口 好的，十分感谢！ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
  
你好，是访问http://127.0.0.1:8080/moti-cloud/admin吗？然后加入拦截器时，
 registry.addInterceptor(new LoginHandlerInterceptor()).addPathPatterns("/**").excludePathPatterns("/","/admin".....);
 这样吗？可是我仍会被重定向到登录页。

**Comment by Eleven-is-cool** [comment]
> 你把moti啥的去掉啊，那东西哪来的？
> […](#)
> ---原始邮件--- 发件人: "Eleven-is-cool"<notifications@github.com&gt; 发送时间: 2020年4月21日 22:21:53 收件人: "373675032/moti-cloud"<moti-cloud@noreply.github.com&gt;; 抄送: "nanfeng"<964879015@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题: Re: [373675032/moti-cloud] 如果去掉QQ登录应该改动哪些呢？ (#4) 请问您使用该项目做些什么呢 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Eleven-is-cool"<notifications@github.com&gt;; 发送时间: 2020年4月20日(星期一) 晚上6:40 收件人: "373675032/moti-cloud"<moti-cloud@noreply.github.com&gt;; 抄送: "小泽"<964879015@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 主题: Re: [373675032/moti-cloud] 如果去掉QQ登录应该改动哪些呢？ (#4) 你可以看源码，登录的controller，内置了一个调试用的借口"/admin""，别忘了在拦截器放开"/admin"接口 好的，十分感谢！ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 你好，是访问[http://127.0.0.1:8080/moti-cloud/admin吗？然后加入拦截器时，](http://127.0.0.1:8080/moti-cloud/admin%E5%90%97%EF%BC%9F%E7%84%B6%E5%90%8E%E5%8A%A0%E5%85%A5%E6%8B%A6%E6%88%AA%E5%99%A8%E6%97%B6%EF%BC%8C) registry.addInterceptor(new LoginHandlerInterceptor()).addPathPatterns("/**").excludePathPatterns("/","/admin".....); 这样吗？可是我仍会被重定向到登录页。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

```http://127.0.0.1:8080/admin```这样是404诶

**Comment by waiting-windy** [comment]
你用的是我的代码吗?不会是用的原作者的吧


 
---原始邮件---
发件人: "Eleven-is-cool"<notifications@github.com&gt;
发送时间: 2020年4月21日 22:25:40
收件人: "373675032/moti-cloud"<moti-cloud@noreply.github.com&gt;;
抄送: "nanfeng"<964879015@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [373675032/moti-cloud] 如果去掉QQ登录应该改动哪些呢？ (#4)




  
你把moti啥的去掉啊，那东西哪来的？
 …
 ---原始邮件--- 发件人: "Eleven-is-cool"<notifications@github.com&gt; 发送时间: 2020年4月21日 22:21:53 收件人: "373675032/moti-cloud"<moti-cloud@noreply.github.com&gt;; 抄送: "nanfeng"<964879015@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题: Re: [373675032/moti-cloud] 如果去掉QQ登录应该改动哪些呢？ (#4) 请问您使用该项目做些什么呢 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Eleven-is-cool"<notifications@github.com&gt;; 发送时间: 2020年4月20日(星期一) 晚上6:40 收件人: "373675032/moti-cloud"<moti-cloud@noreply.github.com&gt;; 抄送: "小泽"<964879015@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 主题: Re: [373675032/moti-cloud] 如果去掉QQ登录应该改动哪些呢？ (#4) 你可以看源码，登录的controller，内置了一个调试用的借口"/admin""，别忘了在拦截器放开"/admin"接口 好的，十分感谢！ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 你好，是访问http://127.0.0.1:8080/moti-cloud/admin吗？然后加入拦截器时， registry.addInterceptor(new LoginHandlerInterceptor()).addPathPatterns("/**").excludePathPatterns("/","/admin".....); 这样吗？可是我仍会被重定向到登录页。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
  
http://127.0.0.1:8080/admin这样是404诶

**Comment by Eleven-is-cool** [comment]
> 你用的是我的代码吗?不会是用的原作者的吧
> […](#)
> ---原始邮件--- 发件人: "Eleven-is-cool"<notifications@github.com&gt; 发送时间: 2020年4月21日 22:25:40 收件人: "373675032/moti-cloud"<moti-cloud@noreply.github.com&gt;; 抄送: "nanfeng"<964879015@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题: Re: [373675032/moti-cloud] 如果去掉QQ登录应该改动哪些呢？ (#4) 你把moti啥的去掉啊，那东西哪来的？ … ---原始邮件--- 发件人: "Eleven-is-cool"<notifications@github.com&gt; 发送时间: 2020年4月21日 22:21:53 收件人: "373675032/moti-cloud"<moti-cloud@noreply.github.com&gt;; 抄送: "nanfeng"<964879015@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题: Re: [373675032/moti-cloud] 如果去掉QQ登录应该改动哪些呢？ (#4) 请问您使用该项目做些什么呢 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Eleven-is-cool"<notifications@github.com&gt;; 发送时间: 2020年4月20日(星期一) 晚上6:40 收件人: "373675032/moti-cloud"<moti-cloud@noreply.github.com&gt;; 抄送: "小泽"<964879015@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 主题: Re: [373675032/moti-cloud] 如果去掉QQ登录应该改动哪些呢？ (#4) 你可以看源码，登录的controller，内置了一个调试用的借口"/admin""，别忘了在拦截器放开"/admin"接口 好的，十分感谢！ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 你好，是访问[http://127.0.0.1:8080/moti-cloud/admin吗？然后加入拦截器时，](http://127.0.0.1:8080/moti-cloud/admin%E5%90%97%EF%BC%9F%E7%84%B6%E5%90%8E%E5%8A%A0%E5%85%A5%E6%8B%A6%E6%88%AA%E5%99%A8%E6%97%B6%EF%BC%8C) registry.addInterceptor(new LoginHandlerInterceptor()).addPathPatterns("/**").excludePathPatterns("/","/admin".....); 这样吗？可是我仍会被重定向到登录页。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. [http://127.0.0.1:8080/admin这样是404诶](http://127.0.0.1:8080/admin%E8%BF%99%E6%A0%B7%E6%98%AF404%E8%AF%B6) — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

啊哈，我以为你就是原作者呀，才发现不是，我是在这里提的issue。

**Comment by waiting-windy** [comment]
额，如果是原作者的那个的话，你就是moti-cloud/admin，然后在数据库里加一个用户id=1，filestore=1，那些数据都可以加。就可以登录了，我是对原作者的二次开发，欢迎学习我的http://lizeyu.club


 
---原始邮件---
发件人: "Eleven-is-cool"<notifications@github.com&gt;
发送时间: 2020年4月21日 22:31:23
收件人: "373675032/moti-cloud"<moti-cloud@noreply.github.com&gt;;
抄送: "nanfeng"<964879015@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [373675032/moti-cloud] 如果去掉QQ登录应该改动哪些呢？ (#4)




  
你用的是我的代码吗?不会是用的原作者的吧
 …
 ---原始邮件--- 发件人: "Eleven-is-cool"<notifications@github.com&gt; 发送时间: 2020年4月21日 22:25:40 收件人: "373675032/moti-cloud"<moti-cloud@noreply.github.com&gt;; 抄送: "nanfeng"<964879015@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题: Re: [373675032/moti-cloud] 如果去掉QQ登录应该改动哪些呢？ (#4) 你把moti啥的去掉啊，那东西哪来的？ … ---原始邮件--- 发件人: "Eleven-is-cool"<notifications@github.com&gt; 发送时间: 2020年4月21日 22:21:53 收件人: "373675032/moti-cloud"<moti-cloud@noreply.github.com&gt;; 抄送: "nanfeng"<964879015@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题: Re: [373675032/moti-cloud] 如果去掉QQ登录应该改动哪些呢？ (#4) 请问您使用该项目做些什么呢 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Eleven-is-cool"<notifications@github.com&gt;; 发送时间: 2020年4月20日(星期一) 晚上6:40 收件人: "373675032/moti-cloud"<moti-cloud@noreply.github.com&gt;; 抄送: "小泽"<964879015@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 主题: Re: [373675032/moti-cloud] 如果去掉QQ登录应该改动哪些呢？ (#4) 你可以看源码，登录的controller，内置了一个调试用的借口"/admin""，别忘了在拦截器放开"/admin"接口 好的，十分感谢！ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 你好，是访问http://127.0.0.1:8080/moti-cloud/admin吗？然后加入拦截器时， registry.addInterceptor(new LoginHandlerInterceptor()).addPathPatterns("/**").excludePathPatterns("/","/admin".....); 这样吗？可是我仍会被重定向到登录页。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. http://127.0.0.1:8080/admin这样是404诶 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
  
啊哈，我以为你就是原作者呀，才发现不是，我是在这里提的issue。

**Comment by Eleven-is-cool** [comment]
> 额，如果是原作者的那个的话，你就是moti-cloud/admin，然后在数据库里加一个用户id=1，filestore=1，那些数据都可以加。就可以登录了，我是对原作者的二次开发，欢迎学习我的http://lizeyu.club
> […](#)
> ---原始邮件--- 发件人: "Eleven-is-cool"<notifications@github.com&gt; 发送时间: 2020年4月21日 22:31:23 收件人: "373675032/moti-cloud"<moti-cloud@noreply.github.com&gt;; 抄送: "nanfeng"<964879015@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题: Re: [373675032/moti-cloud] 如果去掉QQ登录应该改动哪些呢？ (#4) 你用的是我的代码吗?不会是用的原作者的吧 … ---原始邮件--- 发件人: "Eleven-is-cool"<notifications@github.com&gt; 发送时间: 2020年4月21日 22:25:40 收件人: "373675032/moti-cloud"<moti-cloud@noreply.github.com&gt;; 抄送: "nanfeng"<964879015@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题: Re: [373675032/moti-cloud] 如果去掉QQ登录应该改动哪些呢？ (#4) 你把moti啥的去掉啊，那东西哪来的？ … ---原始邮件--- 发件人: "Eleven-is-cool"<notifications@github.com&gt; 发送时间: 2020年4月21日 22:21:53 收件人: "373675032/moti-cloud"<moti-cloud@noreply.github.com&gt;; 抄送: "nanfeng"<964879015@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题: Re: [373675032/moti-cloud] 如果去掉QQ登录应该改动哪些呢？ (#4) 请问您使用该项目做些什么呢 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Eleven-is-cool"<notifications@github.com&gt;; 发送时间: 2020年4月20日(星期一) 晚上6:40 收件人: "373675032/moti-cloud"<moti-cloud@noreply.github.com&gt;; 抄送: "小泽"<964879015@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 主题: Re: [373675032/moti-cloud] 如果去掉QQ登录应该改动哪些呢？ (#4) 你可以看源码，登录的controller，内置了一个调试用的借口"/admin""，别忘了在拦截器放开"/admin"接口 好的，十分感谢！ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 你好，是访问[http://127.0.0.1:8080/moti-cloud/admin吗？然后加入拦截器时，](http://127.0.0.1:8080/moti-cloud/admin%E5%90%97%EF%BC%9F%E7%84%B6%E5%90%8E%E5%8A%A0%E5%85%A5%E6%8B%A6%E6%88%AA%E5%99%A8%E6%97%B6%EF%BC%8C) registry.addInterceptor(new LoginHandlerInterceptor()).addPathPatterns("/**").excludePathPatterns("/","/admin".....); 这样吗？可是我仍会被重定向到登录页。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. [http://127.0.0.1:8080/admin这样是404诶](http://127.0.0.1:8080/admin%E8%BF%99%E6%A0%B7%E6%98%AF404%E8%AF%B6) — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 啊哈，我以为你就是原作者呀，才发现不是，我是在这里提的issue。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

多谢，可以了。已经star。
